### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by TheDiamondYT1** [Vertex-Client/Vertex-Client.github.io#1]
Add a file named CNAME to the repo with the contents being `vertex-client.ml` and save.

Then add 2 an `A records`  with the names `vertex-client.ml` pointing to the IP addresses `192.30.252.153` and `192.30.252.154`.

Now http://vertex-client.ml wont redirect to the github site URL, but will show http://vertex-client.ml.

**Comment by Vertex-Client** [comment]
And where do I exactly enter this? Freenom/Dot.tk's custom DNS is not available:

> ```
> DNS MANAGEMENT for vertex-client.ml
> Back to domain details
> Zone is not active yet.
> ```

**Comment by TheDiamondYT1** [comment]
I use freenom for http://thediamondyt.tk. Let me get a screenshot fir you

**Comment by TheDiamondYT1** [comment]
http://m.imgur.com/hVKXenz

In the blank name spaces you enter vertex-client.ml and after save it will go blank

**Comment by TheDiamondYT1** [comment]
Also i dont get why you made a seperate account for the client and not an organization

**Comment by Vertex-Client** [comment]
I was on the exact same page as you but for me it doesn't show that, it shows 

> Zone is not active yet.

instead.

**Comment by TheDiamondYT1** [comment]
Screenshot?

**Comment by TheDiamondYT1** [comment]
From a site i found:

```
Step 8 : Click on "Manage Freenom DNS". If you get "Zone not active yet" problem then just go to "Management tools" >>> select Nameservers >>> Use Default Nameserver Button and hit Change Nameservers. 
```

**Comment by Vertex-Client** [comment]
Thank you, let's try.

**Comment by TheDiamondYT1** [comment]
Okay btw who is this on the account

**Comment by TheDiamondYT1** [comment]
It works!
